### ISSUE TITLE
demo gh-pages

### ISSUE THREAD

**Issue by forbesjo** [videojs/videojs-contrib-quality-levels#11]
A demo page would be nice

**Comment by iamart** [comment]
@forbesjo it's rather a framework than a plugin. There's nothing to put for a demo

**Comment by forbesjo** [comment]
The idea is to use VHS as the playback engine and show how it works with quality levels

**Comment by gkatsev** [comment]
https://videojs-http-streaming.netlify.app/ has a plugin that uses this API.
