### ISSUE TITLE
Can we hide a specific quality level for video-js-http-source-selector plugin?

### ISSUE THREAD

**Issue by kvpasupuleti** [videojs/videojs-contrib-quality-levels#123]
## Description
Can we hide a specific quality level for video-js-http-source-selector plugin?

### Expected
1. Video should load and will have multiple quality levels ranging from 240 - 1080
2. If we disable 1080 programmatically, only quality levels from 240-720 should be shown

### plugins
video-js-http-source-selector

**Comment by gkatsev** [comment]
Removing levels is out of scope for this plugin. If you want to hide certain items, I would recommend asking if that's something that the videojs-http-source-selector plugin would provide.
