### ISSUE TITLE
"TypeError: this.player.qualityLevels is not a function"

### ISSUE THREAD

**Issue by tudacoding** [videojs/videojs-contrib-quality-levels#124]
## Description
catch error player.qualityLevels is not a function

I'm using Vuejs and implement video.js for play video hls. I want to change quality of hls video and installed videojs-contrib-quality-levels but still not working. ( Video.js version 7.11.5 has been stabled in my system so i don't want to change version of videoJS ). Any solution? Thanks so much 

## Environment
"vue": "^2.6.11"
"video.js": "7.11.5"
"videojs-contrib-quality-levels": "^2.0.9",

![image](https://user-images.githubusercontent.com/32331243/107322012-37676280-6ad6-11eb-8e86-76afb4a702bd.png)

**Comment by tudacoding** [comment]
![image](https://user-images.githubusercontent.com/32331243/107322384-f58aec00-6ad6-11eb-9a81-ff945288595d.png)

**Comment by gkatsev** [comment]
Has the only change you've made to update to Video.js 7.11? We got a similar report here https://github.com/videojs/video.js/issues/7091

**Comment by yougotwill** [comment]
If anyone else has this issue. Might be really obvious but make sure to directly import the package wherever you  are using it. i.e. `import "videojs-contrib-quality-levels";`.

**Comment by beedrill** [comment]
> If anyone else has this issue. Might be really obvious but make sure to directly import the package wherever you are using it. i.e. `import "videojs-contrib-quality-levels";`.

Thanks a lot, that works! Can't believe they didn't include this step in the document...
