### ISSUE TITLE
Not working with videojs-contrib-dash

### ISSUE THREAD

**Issue by alpkahveci** [videojs/videojs-contrib-quality-levels#126]
## Description
Quality selector is not working when use videojs-contrib-dash .(i m using contrib-dash because of DRM). When i comment out videojs-contrib-dash it is working.

I could not find the reason. maybe it is about videojs-contrib-dash i dont know. Please help me.

### plugins

    "video.js": "^7.10.2",
    "videojs-contrib-quality-levels": "^2.0.9",
    "videojs-contrib-dash": "^5.0.0",

**Comment by gkatsev** [comment]
Unfortunately, videojs-contrib-dash never got support for this plugin.

**Comment by alpkahveci** [comment]
ah sorry, when i import videojs-contib-dash plugin not dash.js, quality selector is not working. player.qualityLevels() return empty data. please help @gkatsev

**Comment by gkatsev** [comment]
As I mentioned before, videojs-contrib-dash doesn't support this currently. It's not something we have the bandwidth to implement ourselves right now.
