### ISSUE TITLE
Can not get qualityLevels.length, it is zero.

### ISSUE THREAD

**Issue by WeBBLiu** [videojs/videojs-contrib-quality-levels#13]
Hi,
Please look at [jsbin](http://jsbin.com/wogebu/edit?html,output), I can not obtain the length of qualitylevels.
Thanks

**Comment by forbesjo** [comment]
Looks like you'll have to listen to the `addqualitylevel` event because `player.qualityLevels()` is not populated yet.
Here's an example
http://jsbin.com/givolim/1/edit?html,console,output

@mjneil I think we should update the README to instruct the proper usage of the plugin

**Comment by WeBBLiu** [comment]
http://jsbin.com/vagelic/edit?js,console,output
