### ISSUE TITLE
How to properly create qualityLevels from sources?

### ISSUE THREAD

**Issue by mateusz-wyka** [videojs/videojs-contrib-quality-levels#143]
## Description
I have sources:
```
const sources = [
  {
    src: assets(hdVideo),
    type: "video/mp4",
    label: "1080p"
  },
  {
    src: assets(sdVideo),
    type: "video/mp4",
    label: "480p"
    }
];
```

How to properly create qualityLevels from these sources?

**Comment by adrums86** [comment]
Hi @mateusz-wyka I would take a look at the docs here for populating the qualityLevels list: https://github.com/videojs/videojs-contrib-quality-levels?tab=readme-ov-file#populating-the-list
The rendition-mixin code also provides an example of how this all works together with [VHS](https://github.com/videojs/http-streaming).
https://github.com/videojs/http-streaming/blob/main/src/rendition-mixin.js
