### ISSUE TITLE
unable to change quality on stream in newest version

### ISSUE THREAD

**Issue by dygy** [videojs/videojs-contrib-quality-levels#146]
## Description
i'm unable to change quality, streams runs the same one anyway
codepen [here](https://codepen.io/Dygy/pen/qBgRJop).

## Steps to reproduce
1. enter my codepen
2. check my code
3. try to push quality buttons down there

### Expected
quality can be changed 
### Actual
quality are still the same even due console log says it's changed, video are still same

#### videojs
8.6.1
#### browsers
any
#### OSes
mac os

### plugins
[videojs-contrib-quality-levels](https://github.com/videojs/videojs-contrib-quality-levels)

**Comment by dygy** [comment]
it seems i was wrong at understanding arch. i shoud 
                    Array.from(qualityLevels).forEach((elem) => {
                        elem.enabled = *statement*;
                    });
i fought i can enable singe quality and it's all fine, but i should disable all others (maybe improve request???)

**Comment by gkatsev** [comment]
That's working as expected. We want to be able to select which renditions are enabled or not to give a hind to the ABR algorithm which renditions it's allowed to switch between.

See https://github.com/videojs/videojs-contrib-quality-levels#triggering-the-change-event for switching to a specific rendition.

**Comment by dygy** [comment]
it's okay, it was just unexpected by me, but when i found out how it work, it's all good. Just not pretty understandable
