### ISSUE TITLE
strange transitions

### ISSUE THREAD

**Issue by campones** [videojs/videojs-contrib-quality-levels#15]
hi
so I update to the last videojs, last video-contrib-hls, and your script.

I have been streaming a 2 resolution level playlist and since I have a rather bad internet, I just put some download file and youtube at the same time, to see that the script catch the lowest res when my internet is low.  which is what is expected, so that's great.  It also catch back the highest res when my bandwidth get better  (ie stopping youtube).

My issue is more about the transition, when it takes the lowest, it download a segment that was previously downloaded on the other resolution and eventually starts to downloads segments twice of the same resolution

https://i.gyazo.com/9397b320708d2fa93057e57b68dbb9cf.png

edit: i made sure that my 2 playlist (from the master playlist) had similar numbered segment at the same time, that could have explained the problem.

**Comment by forbesjo** [comment]
This question would be better suited for github.com/videojs/videojs-contrib-hls since this involves segment fetching logic. Could you open a new issue in that project?
