### ISSUE TITLE
Error with qualityLevels.on

### ISSUE THREAD

**Issue by Jimgitsit** [videojs/videojs-contrib-quality-levels#152]
## Description
Briefly describe the issue.
TypeError: qualityLevels.on is not a function

## Steps to reproduce
Example code

### Expected
Get quality levels.

### Actual
Error

### Error output
TypeError: qualityLevels.on is not a function

#### videojs
8.17.1

#### browsers
Chrome

#### OSes
Windows

**Comment by adrums86** [comment]
This doesn't have enough info for us to do anything with. Closing for now. Feel free to create a new issue or update this with more information if necessary.
