### ISSUE TITLE
can not work with video.js 5.20.1  videojs-contrib-hls  * @version 5.8.1

### ISSUE THREAD

**Issue by louishot** [videojs/videojs-contrib-quality-levels#19]
Hello,

I try to use it 

`<link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/5.20.1/alt/video-js-cdn.css" rel="stylesheet">

  <link href="https://players.brightcove.net/videojs-thumbnails/videojs.thumbnails.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/5.20.1/alt/video.novtt.js"></script>

  <script src="https://unpkg.com/videojs-contrib-quality-levels@2.0.3/dist/videojs-contrib-quality-levels.js"></script>

  <script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script>

  <script src="https://players.brightcove.net/videojs-thumbnails/videojs.thumbnails.js"></script>

</head>
<body>

  <video id="video" class="video-js" controls preload="none" width="958" height="408"
  data-setup='{"techOrder": ["html5", "flash"]}'>
      
    <source src="https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8" type="application/x-mpegURL">
      
  </video>

<script>
  var player = videojs('video');

  player.qualityLevels();
</script>`

**Comment by mjneil** [comment]
What issues are you experiencing? Is it just that the list is empty? The quality level list will initially be empty and won't be populated until after it has finished downloading the master manifest. You can listen to the `addqualitylevel` event to be notified when quality levels are added to the list

```
var player = videojs('video');
player.qualityLevels().on('addqualitylevel', function(event) {
  console.log(event.qualityLevel);
});
```

**Comment by buccfer** [comment]
@mjneil in chrome for android the list is always empty.. is there any known issue or anything I'm missing?

**Comment by mjneil** [comment]
@buccfer are you overriding androids native hls playback? https://github.com/videojs/videojs-contrib-hls#overridenative If you don't do this then the list will be empty because native playback will be used

**Comment by buccfer** [comment]
@mjneil I just did and it's working now.. thanks!

**Comment by buccfer** [comment]
@mjneil Using overrideNative makes Safari to fail after a random amount of time. As stated here https://github.com/videojs/videojs-contrib-hls/issues/1005. Do you know how to fix this?

Best.

**Comment by mostafamashayekhi** [comment]
@mjneil @buccfer  can you explain with example code how to overriding androids native hls and fixed empty list in android chrome I'm newbie in vidoejs , thanks
