### ISSUE TITLE
No levels available in Safari

### ISSUE THREAD

**Issue by EJIqpEP** [videojs/videojs-contrib-quality-levels#20]
Hi. Thank you for awesome plugin. For me it works smoothly in all browsers except Safari (web and mobile). The addqualitylevel is not firing in Safari at all. And even when I check levels after some time there are no levels available.
```
player.qualityLevels().on('addqualitylevel', function(event) {})
```

Can you recommend any workaround for it? Here is an example where it doesn't work.

http://jsbin.com/vagelic/edit?js,console,output

**Comment by mjneil** [comment]
videojs-contrib-hls lets Safari's native HLS implementation take control. There is not an api in safari to extract the quality level information or to manually enable/disable levels, so quality levels will be unavailable in safari. One workaround you could do is to [override safari's native playback with videojs-contrib-hls using some options](https://github.com/videojs/videojs-contrib-hls#overridenative) however we have seen playback issues in the past with this and recommend letting Safari's native playback takeover

**Comment by EJIqpEP** [comment]
Awesome. Thanks for such a quick answer.

**Comment by vmangelovv** [comment]
@mjneil do you know this workaround is only for desktop Safari. Mobile safari does not support it.
I have to know if that is true. Wyt? (https://github.com/videojs/videojs-contrib-hls/issues/1005#issuecomment-339042409)

**Comment by gkatsev** [comment]
It's not possible on iPhones because Safari there doesn't contain the relevant APIs (it doesn't have MSE), but on desktop and ipados, you can set `overrideNative: true`, though, we wouldn't recommend it because we don't generally test our playback engine in those browsers.
