### ISSUE TITLE
Frequently changed quality proving error

### ISSUE THREAD

**Issue by sudhyer** [videojs/videojs-contrib-quality-levels#21]
I have added quality level plugin with custom UI. when I am changing quality frequently then getting error.

Can not read property 'playlist' undefined in 3800 line of hls plugin.
 
![error](https://user-images.githubusercontent.com/29208481/29489611-b4e90d9e-8542-11e7-8b82-29e9689f7515.png)

**Comment by mjneil** [comment]
Sounds like the issue this is trying to fix https://github.com/videojs/videojs-contrib-hls/pull/1207
In the mean time, I would suggest making sure there is at least one quality enabled. If you are cycling through the levels and disabling them all before enabling the desired, try making sure that the one that is already enabled stays enabled until youve also enabled the desired level

**Comment by sudhyer** [comment]
Thanks mjneil. I think I was disabling all quality first then enabled. now fixed.
