### ISSUE TITLE
cdnjs and dist folder

### ISSUE THREAD

**Issue by volkirik** [videojs/videojs-contrib-quality-levels#23]
hello,

I do not use npm or bower. 

Could you please submit the resulting file to cdnjs and also create dist folder in github containing resulting videojs-contrib-quality-levels.js file?

If you will not, could you please explain why? Thanks!

**Comment by mjneil** [comment]
Hi @volkirik, sorry for not getting back to you sooner. You can get the dist from unpkg https://unpkg.com/videojs-contrib-quality-levels@2.0.4/dist/videojs-contrib-quality-levels.min.js 

We will try to remember to upload the dist files to the github releases section in the future
