### ISSUE TITLE
Update video js dependency

### ISSUE THREAD

**Issue by sundaykuhk01** [videojs/videojs-contrib-quality-levels#24]
I am using webpack with video js 6
When I import 'videojs-contrib-quality-levels', both video js 5 and 6 is loaded into webpack

Will this package be updated to version 3.0.0 which depends on video js 6?

Thanks a lot!

**Comment by gesinger** [comment]
Hey @sundaykuhk01 , thank you for the issue and for submitting https://github.com/videojs/videojs-contrib-quality-levels/pull/25 . The PR is now merged and a part of videojs-contrib-quality-levels v2.0.4.

Please let us know if you encounter any more issues. Thanks again.
