### ISSUE TITLE
Create react app build ERROS

### ISSUE THREAD

**Issue by inerc** [videojs/videojs-contrib-quality-levels#41]
Guys, good afternoon.
There was a problem with the assembly of the project. That's kind of. We use
'create react app'
```
"video.js": "^7.0.5",
"videojs-contrib-hls": "5.13.0",
"videojs-contrib-quality-levels": "^2.0.5",
```

<img width="855" alt="2018-07-09 18 05 58" src="https://user-images.githubusercontent.com/15797209/42458785-1cc653c2-83a3-11e8-844c-6a2046aa88ec.png">

Maybe you know the reasons?

**Comment by gkatsev** [comment]
That file uses ES module imports and if the minifier doesn't support that syntax and runs before things get compiled down to other things, it'll fail.

**Comment by inerc** [comment]
@gkatsev Thank you very much for the answer. Is it possible to fix it?

**Comment by inerc** [comment]
The problem was on our side. Thank you
