### ISSUE TITLE
Missing stylesheets

### ISSUE THREAD

**Issue by icamys** [videojs/videojs-contrib-quality-levels#44]
Version 2.0.5 misses `dist/videojs-contrib-quality-levels.css` that is defined in [package.json](https://github.com/videojs/videojs-contrib-quality-levels/blob/master/package.json#L40).

**Comment by gesinger** [comment]
Thanks for reporting @icamys . Looks like we have a lingering reference to a stylesheet (probably from the plugin generator) that we never cleaned up. We'll clean up the package.json.

**Comment by mjneil** [comment]
Fixed
