### ISSUE TITLE
After changing the enabled levels it takes a while to reflect the change

### ISSUE THREAD

**Issue by luisbritescarvalho** [videojs/videojs-contrib-quality-levels#47]
## Description
Despite of starting to download immediately the new resolution after switching it takes a while to actually change the resolution on the player. It's very clear when toggling between 180p to 720p.  Am I missing something?

## Test url: 
https://98w7m059jp.codesandbox.io/

### Expected
I expect that when we switch from 180p to 1080p it plays with 1080p right after receiving the first segments.

### versions
video.js: "7.1.0"
videojs-contrib-quality-levels: "2.0.5"

**Comment by forbesjo** [comment]
This should be fixed with video.js 7.2.2, please let us know if this is still an issue for you

**Comment by luisbritescarvalho** [comment]
Yes, it's fixed. Thanks!
