### ISSUE TITLE
Standalone Version

### ISSUE THREAD

**Issue by mrcolak** [videojs/videojs-contrib-quality-levels#71]
Hello,

I am using Video.js 5.19.2 with HLS plugin.

Is there any standalone version of your plugin? I dont have nodejs.

**Comment by mjneil** [comment]
I'm assuming that you are looking for the built script file you can include in your page without needing to use npm or a bundler? If so, you can get the dist file from [unpkg](https://unpkg.com/#/). You can either use unpkg to host the script for you or download and host yourself (recommended for a production environment)

https://unpkg.com/videojs-contrib-quality-levels@2.0.9/dist/videojs-contrib-quality-levels.min.js
