### ISSUE TITLE
Editing quality list

### ISSUE THREAD

**Issue by amirmasoud** [videojs/videojs-contrib-quality-levels#82]
## Description
m3u8 playlist only has `BANDWIDTH` with not `WIDTH` or `HEIGHT`, the output is `undefined`.

## Question
How to handle QualityList based on bitrate? any way to edit the quality list without creating a new one?

**Comment by jawngee** [comment]
@amirmasoud 

You can do it manually:

```javascript
player.qualityLevels().on('addqualitylevel', (event) => {
    let qualityLevel = event.qualityLevel;
    if (qualityLevel.bitrate == 1756000) {
        qualityLevel.width = 1280;
        qualityLevel.height = 720;
    } else if (qualityLevel.bitrate == 704000) {
        qualityLevel.width = 640;
        qualityLevel.height = 360;
    }
});
```

(this works with videojs-http-source-selector)

**Comment by amirmasoud** [comment]
Thanks @jawngee 
It's been a while from the issue, I think I just stayed with auto switcher at the time.
