### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by stevendesu** [videojs/videojs-contrib-quality-levels#90]
This is the ***exact*** same issue that I had with `videojs-contrib-ads`. For details, see: https://github.com/videojs/videojs-contrib-ads/issues/480

## Description

When multiple instances of VideoJS exist, there is no way to specify which instance `videojs-contrib-quality-levels` should bind to. Worse yet, it creates its own personal instance of VideoJS when included as a submodule in a project

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

 1. Create a new project
 2. `npm install --save video.js videojs-contrib-quality-levels`
 3. In your entrypoint: `const videojs = require("video.js/core")` and `require("videojs-contrib-quality-levels")`
 4. Attempt to initialize the qualityLevels plugin: `videojs("myPlayer", { plugins: { qualityLevels: {} } });`

### Expected
The player initializes properly

### Actual
Plugin `qualityLevels` is not found

### Error output
```
Error: plugin "qualityLevels" does not exist core.js:20125
    Player core.js:20125
    forEach (index):262
    Player core.js:20121
    videojs$1 core.js:24803
    js index.js:4
    Webpack 3
    
    __webpack_require__
    
    <anonymous>
    
    <anonymous>
```

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
v7.4.1

#### browsers
All

#### OSes
All

### plugins
None

**Comment by gkatsev** [comment]
Hey, this is a larger Video.js ecosystem issue that we're aware of. See the long discussion here https://github.com/videojs/video.js/issues/5223. It's definitely something that we want to fix but it's kind of tricky. The current workaround would be to use webpack to alias `video.js` to `video.js/core` in node_modules.

Another thing to think about, which I'm not sure was brought up in videojs/video.js#5223 (there's likely a separate issue for that) is whether it's time to switch from direct dependencies to peer dependencies.

**Comment by stevendesu** [comment]
@gkatsev Thanks for the heads up -- looks like this is an issue some others have had before :) I'll reference my two issues there so we don't lose the use cases I described or the hack-y solution I found for submodule plugins, then I'll close the two issues I opened on `videojs-contrib-ads` and `videojs-contrib-quality-levels`

**Comment by gkatsev** [comment]
no problem. Yeah, you're examples are useful. And it's something we've really wanted to fix for a long time but things that ended up being more important kept creeping in, unfortunately.
