### ISSUE TITLE
qualityLevels with length 0

### ISSUE THREAD

**Issue by msjh80311** [videojs/videojs-contrib-quality-levels#91]
## Description
I've found that issue videojs/videojs-contrib-quality-levels#13 described a similar problem, and the reply told to use eventListener to `addqualitylevel`.
I followed, but it seems like it just didn't get to those lines.

my codes are like:
```let qualityLevels = player.qualityLevels();
  qualityLevels.on('addqualitylevel', function(event) {
    let qualityLevel = event.qualityLevel;
    console.log('qualityLevel.height:', qualityLevel.height);  // logs not printed
  });
```

What's more weird is, this problem doesn't always happen.

Users seldom encounter.
And I can only tell that **when my document is hidden during the initializing of the player, there's a lot more chance to happen!**  

### Expected
I could get all the tracks(sources) of my video via player.qualityLevels(). 

### Actual
Problems that `addqualitylevel` seldom not works. `player.qualityLevels()` is an empty list.

### Error output
no error message displayed at all...

#### videojs
7.5.0+

#### browsers
desktop chrome, safari

### plugins
- videojs-ima (1.5.1)
- videojs-contrib-ads (6.6.2)
- videojs-contrib-quality-levels (2.0.9)

**Comment by nikhilpaliwal129** [comment]
Hi,
I am facing a similar issue.
i.e. getting the empty array of levels in the "player.qualityLevels()" object in **chrome version 72**.
is there any solution for it

Plugins:
- "videojs-contrib-quality-levels": "^2.0.9"
-  "video.js": "^7.6.5"

**Comment by OCharnyshevich** [comment]
Hi, try to use
`console.log('qualityLevel.height:', event.qualityLevel.height);`

**Comment by gkatsev** [comment]
If someone can provide a reduced test case we can take a look, however, we haven't seen this issue ourselves.
